export {default as Banner} from './Banner'
export {default as Contact} from './Contact'
export {default as Footer} from './Footer'
export {default as NavBar} from './NavBar'
export {default as Projects} from './Projects'
export {default as Skills} from './Skills'
